spring.application.name=test
server.port=8085

# ===============================
# Conexion a PostgreSQL Docker
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/cafetin

spring.datasource.username=postgres
spring.datasource.password=camilo200804
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# Hibernate JPA
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
