version: '3.8'

services:
  database_aerolinea:
    image: postgres:15-alpine
    container_name: postgres_aerolinea

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: camilo200804
      POSTGRES_DB: aerolinea

    ports:
      - "5433:5432"

    volumes:
      - ./Adr_Database.sql:/docker-entrypoint-initdb.d/init.sql

    restart: unless-stopped